#!/bin/sh

# Colors
ESC_SEQ="\x1b["
RESET=$ESC_SEQ"39;49;00m"
RED=$ESC_SEQ"31;01m"
GREEN=$ESC_SEQ"32;01m"
YELLOW=$ESC_SEQ"33;01m"
BLUE=$ESC_SEQ"34;01m"
MAGENTA=$ESC_SEQ"35;01m"
CYAN=$ESC_SEQ"36;01m"

spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep -w "$pid" )" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

action () {
	/bin/echo -e "\n$BLUE ⇒  $1...$RESET"
}

running () {
    spinner $!
    /bin/echo ""
}

bot () {
	/bin/echo -e "\n$CYAN\[ ._. ]/ - $1$RESET"
}

success () {
	/bin/echo -e "$GREEN [ OK ] $1 $RESET"
}

fail () {
	/bin/echo -e "$RED [ FAILED ] $1 $RESET"
}

warning () {
	/bin/echo -e "$YELLOW [ WARNING ] $1 $RESET"
}