#!/usr/bin/env fish

abbr -a y 'yarn'
abbr -a ya 'yarn add'
abbr -a yad 'yarn add -D'
abbr -a yad 'yarn add --dev'
abbr -a yag 'yarn add global'
abbr -a yap 'yarn add --peer'
abbr -a yb 'yarn build'
abbr -a yba 'yarn build --analyze'
abbr -a yc 'yarn create'
abbr -a ycc 'yarn cache clean'
abbr -a ycl 'yarn clean'
abbr -a yd 'yarn dev'
abbr -a ydv 'yarn develop'
abbr -a yg 'yarn generate'
abbr -a yga 'yarn global add'
abbr -a ygls 'yarn global list'
abbr -a ygrm 'yarn global remove'
abbr -a ygu 'yarn global upgrade'
abbr -a yh 'yarn help'
abbr -a yi 'yarn init'
abbr -a yin 'yarn install'
abbr -a yls 'yarn list'
abbr -a yout 'yarn outdated'
abbr -a yp 'yarn pack'
abbr -a yrm 'yarn remove'
abbr -a yrun 'yarn run'
abbr -a ys 'yarn serve'
abbr -a yst 'yarn start'
abbr -a yt 'yarn test'
abbr -a ytc 'yarn test --coverage'
abbr -a yuc 'yarn global upgrade; and yarn cache clean'
abbr -a yui 'yarn upgrade-interactive'
abbr -a yup 'yarn upgrade'
abbr -a yupl 'yarn upgrade --latest'
abbr -a yv 'yarn version'
abbr -a yw 'yarn workspace'
abbr -a yws 'yarn workspaces'